import { TouristSite, Booking, Review, Notification } from '../types';

export const mockTouristSites: TouristSite[] = [
  {
    id: '1',
    title: 'Tour por la Sagrada Familia',
    description: 'Descubre la obra maestra de Gaudí con un guía experto. Incluye entrada sin colas.',
    location: 'Barcelona, España',
    price: 45,
    category: 'Cultura',
    images: ['https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800'],
    providerId: '2',
    providerName: 'Barcelona Tours',
    rating: 4.8,
    reviews: 342,
    availability: true,
    coordinates: { lat: 41.4036, lng: 2.1744 },
  },
  {
    id: '2',
    title: 'Senderismo en los Picos de Europa',
    description: 'Aventura de día completo por rutas espectaculares. Incluye guía y almuerzo.',
    location: 'Asturias, España',
    price: 65,
    category: 'Aventura',
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
    providerId: '2',
    providerName: 'Mountain Adventures',
    rating: 4.9,
    reviews: 189,
    availability: true,
    coordinates: { lat: 43.1828, lng: -4.8551 },
  },
  {
    id: '3',
    title: 'Cata de Vinos en La Rioja',
    description: 'Visita a 3 bodegas premium con degustación de vinos y tapas locales.',
    location: 'La Rioja, España',
    price: 55,
    category: 'Gastronomía',
    images: ['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800'],
    providerId: '2',
    providerName: 'Wine Experience',
    rating: 4.7,
    reviews: 256,
    availability: true,
    coordinates: { lat: 42.4627, lng: -2.4450 },
  },
  {
    id: '4',
    title: 'Paddle Surf en Costa Brava',
    description: 'Sesión de paddle surf en las mejores calas. Equipo incluido.',
    location: 'Girona, España',
    price: 35,
    category: 'Deportes',
    images: ['https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800'],
    providerId: '2',
    providerName: 'Water Sports CB',
    rating: 4.6,
    reviews: 178,
    availability: true,
    coordinates: { lat: 41.8919, lng: 3.1275 },
  },
  {
    id: '5',
    title: 'Tour Nocturno por Madrid',
    description: 'Descubre los secretos de Madrid de noche. Incluye tapas y bebidas.',
    location: 'Madrid, España',
    price: 40,
    category: 'Cultura',
    images: ['https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800'],
    providerId: '2',
    providerName: 'Madrid Nights',
    rating: 4.5,
    reviews: 423,
    availability: true,
    coordinates: { lat: 40.4168, lng: -3.7038 },
  },
  {
    id: '6',
    title: 'Paseo en Globo por Segovia',
    description: 'Vuela sobre los paisajes castellanos al amanecer. Incluye brunch.',
    location: 'Segovia, España',
    price: 180,
    category: 'Aventura',
    images: ['https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800'],
    providerId: '2',
    providerName: 'Balloon Adventures',
    rating: 5.0,
    reviews: 145,
    availability: true,
    coordinates: { lat: 40.9429, lng: -4.1088 },
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'b1',
    siteId: '1',
    siteName: 'Tour por la Sagrada Familia',
    userId: '3',
    userName: 'Juan Usuario',
    date: '2025-11-15',
    status: 'confirmed',
    price: 45,
    guests: 2,
  },
  {
    id: 'b2',
    siteId: '3',
    siteName: 'Cata de Vinos en La Rioja',
    userId: '3',
    userName: 'Juan Usuario',
    date: '2025-11-20',
    status: 'pending',
    price: 55,
    guests: 2,
  },
  {
    id: 'b3',
    siteId: '2',
    siteName: 'Senderismo en los Picos de Europa',
    userId: '3',
    userName: 'Ana García',
    date: '2025-10-10',
    status: 'completed',
    price: 65,
    guests: 4,
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r1',
    siteId: '1',
    userId: '3',
    userName: 'María López',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    rating: 5,
    comment: 'Experiencia increíble! El guía fue muy profesional y aprendimos mucho sobre la historia.',
    date: '2025-10-15',
  },
  {
    id: 'r2',
    siteId: '1',
    userId: '4',
    userName: 'Carlos Ruiz',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    rating: 4,
    comment: 'Muy recomendable. La única pega es que había mucha gente, pero el tour estuvo genial.',
    date: '2025-10-12',
  },
  {
    id: 'r3',
    siteId: '2',
    userId: '5',
    userName: 'Laura Martínez',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400',
    rating: 5,
    comment: 'Las vistas son espectaculares y el almuerzo delicioso. Totalmente recomendado!',
    date: '2025-10-08',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'success',
    title: 'Reserva Confirmada',
    message: 'Tu reserva para "Tour por la Sagrada Familia" ha sido confirmada.',
    read: false,
    createdAt: '2025-10-24T10:30:00',
  },
  {
    id: 'n2',
    type: 'info',
    title: 'Nueva Promoción',
    message: 'Descuento del 20% en tours de aventura este fin de semana.',
    read: false,
    createdAt: '2025-10-24T09:00:00',
  },
  {
    id: 'n3',
    type: 'warning',
    title: 'Recordatorio',
    message: 'Tu experiencia en La Rioja es mañana a las 10:00.',
    read: true,
    createdAt: '2025-10-23T18:00:00',
  },
];
